### ISSUE TITLE
Index 페이지 comments 데이터 불러오기

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#17]
### Background

* `routes/users.js` : MySQL 서버와의 통신 코드를 확인합니다.

* `connection.query()` 의 인자로 SQL Query를 DB Server로 전달할 수 있습니다. 질의 결과는 results 변수에 담깁니다.

### Todo

- [ ] 위와 동일하게 `routes/index.js` 에서도 MySQL 통신을 통해 comments 테이블의 정보를 가져옵니다. 

- [ ] 가져온 테이블 오브젝트를 `views/index.ejs`에게 `res.render()` 를 통해 전달합니다.

- [ ] `views/index.ejs` : `views/users.ejs` 를 참고하여 EJS 문법을 통해 div 태그 내에 comments 테이블의 content 항목들을 나타냅니다. (`ul` 태그와 `li` 태그 사용)

**Comment by sochubert** [comment]
지원~
