### ISSUE TITLE
Index 페이지 DB insert와 연동

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#18]
### Background

* index 페이지에서 button을 클릭했을 시 input 태그 내의 값과 함께 서버로 POST 요청을 합니다.

* 서버에서는 POST 요청에 대한 처리로 DB의 comments 테이블에 새로운 row를 insert 합니다.

### Todo

- [ ] `views/index.ejs` : button 클릭 시 input value와 함께 `localhost:3000/addComment` 주소로 POST 요청하도록 수정합니다.

- [ ] `routes/index.js` : `localhost:3000/addComment` 주소로 POST 요청 시 DB 서버로 적절한 Insert query를 작성합니다.

- [ ] `routes/index.js` : 정상적으로 insert 되었다는 것을 확인 후 POST 요청의 응답으로 index 페이지로 `redirection` 합니다.

**Comment by cwyoon-99** [comment]
제가 할께여
